const copy = {
  en: {
    home_kicker: "Your campus, organized", home_greeting: "Good to see you", home_next: "Your next step",
    home_clear_title: "You are clear for now", home_clear_body: "Add a deadline or join an activity and Elysium will keep the next move visible.",
    home_ask_title: "Ely", home_ask_body: "Get a focused answer based on your university, schedule, and goals.",
    home_upcoming: "Coming up", home_for_you: "Recommended for you", home_social: "Meet people", home_study: "Study together",
    home_academic: "Academic help", home_tools: "Quick tools", home_deadline: "Deadline", home_event: "Social activity", home_session: "Study group",
    see_all: "See all", open: "Open", join: "Join", joined: "Joined", leave: "Leave", request: "Contact on WhatsApp", contact: "WhatsApp",
    discover_title: "Discover campus", discover_body: "Find people, study groups, and activities that match how you want to spend your week.",
    discover_search: "Search by subject, activity, course, or person", discover_social: "Social", discover_sessions: "Study groups",
    discover_groups: "Study groups", discover_tutors: "Tutors", discover_helpers: "Peer helpers", discover_empty: "Nothing matches this search yet.",
    create_social: "Create social event", create_session: "Create study group", add_deadline: "Add deadline", ask_elysium: "Ely",
    calendar_title: "My calendar", calendar_body: "Deadlines and the activities you joined, in one timeline.", calendar_upcoming: "Upcoming",
    calendar_past: "Past", calendar_empty: "Nothing is scheduled yet.", tools_title: "Student toolkit",
    tools_body: "Calculate, revise, find trusted help, and reach official university resources.", tutors: "Private tutors", helpers: "Peer helpers",
    no_upcoming: "No upcoming items", due_today: "Due today", tomorrow: "Tomorrow", days: "days", pending: "Pending",
    request_sent: "WhatsApp opened", subject: "Subject", preferred_time: "Preferred date and time", message: "Message", send_request: "Open WhatsApp",
    profile_public_note: "Public information: your name, subjects, bio, and contact details only when you consent.", profile_helper_note: "Share personal student experience. This is peer support, not an official university role.",
    profile_setup_helper: "Set up peer helper profile", profile_active: "Active", profile_pending: "Pending approval", profile_visible: "Visible", profile_hidden: "Hidden", profile_hide: "Hide", profile_show: "Show",
    profile_subjects: "Subjects, separated by commas", profile_phone: "Phone or WhatsApp", profile_tutor_bio: "Short bio and teaching experience", profile_contact_consent: "I agree to show my contact details to students",
    profile_help_topics: "Help topics, separated by commas", profile_helper_bio: "What can you help other students with?", profile_availability: "Availability", profile_public_contact: "Show my contact details publicly", profile_contact: "WhatsApp or email", profile_my_groups: "My study groups",
    onboarding_step: "Step", onboarding_of: "of", onboarding_language_title: "Choose your language", onboarding_language_body: "You can switch between English, Hebrew, and Arabic at any time.", onboarding_name: "Preferred name",
    onboarding_university_title: "Tell us where you study", onboarding_university_body: "This keeps activities, help, and official resources relevant to your campus.", onboarding_no_university: "No universities have been added yet. You can continue and choose one later.", onboarding_year: "Academic year", onboarding_field: "Field of study", onboarding_field_search: "Start typing, select a field, or add yours", onboarding_field_select: "Select a suggested field or keep what you typed",
    onboarding_courses_title: "Shape your campus feed", onboarding_courses_body: "Courses are optional. Interests help Elysium recommend useful people, sessions, and activities.", onboarding_courses: "Courses, separated by commas", onboarding_courses_optional: "Optional. You can start with no courses and add them later.", onboarding_interests: "Interests and hobbies", onboarding_interest_search: "Search hobbies", onboarding_add_interest: "Add a hobby", onboarding_interest_en: "English name", onboarding_interest_he: "Hebrew name", onboarding_interest_save: "Add hobby", onboarding_interest_duplicate: "That hobby already exists, so we selected it for you.",
    onboarding_help_title: "What should Elysium help with?", onboarding_help_body: "Choose any that matter now, or continue without selecting one.", onboarding_back: "Back", onboarding_continue: "Continue", onboarding_finish: "Enter Elysium", onboarding_side_note: "Elysium adapts the home screen to your campus, interests, and current needs.", campus: "Campus", your_university: "Your university",
  },
  he: {
    home_kicker: "הקמפוס שלך, מסודר", home_greeting: "טוב לראות אותך", home_next: "הצעד הבא שלך",
    home_clear_title: "הכול מסודר כרגע", home_clear_body: "הוסיפו מועד או הצטרפו לפעילות ו-Elysium תשמור את הצעד הבא מול העיניים.",
    home_ask_title: "Ely", home_ask_body: "קבלו תשובה ממוקדת לפי האוניברסיטה, לוח הזמנים והמטרות שלכם.",
    home_upcoming: "מה צפוי", home_for_you: "מומלץ עבורך", home_social: "להכיר אנשים", home_study: "ללמוד יחד",
    home_academic: "עזרה אקדמית", home_tools: "כלים מהירים", home_deadline: "מועד אחרון", home_event: "פעילות חברתית", home_session: "מפגש לימוד",
    see_all: "הצג הכול", open: "פתוח", join: "הצטרפות", joined: "הצטרפת", leave: "עזיבה", request: "בקשת שיעור", contact: "יצירת קשר",
    discover_title: "מגלים את הקמפוס", discover_body: "מצאו אנשים, מפגשים ופעילויות שמתאימים לשבוע שלכם.",
    discover_search: "חיפוש לפי נושא, פעילות, קורס או אדם", discover_social: "חברתי", discover_sessions: "מפגשי לימוד",
    discover_groups: "קבוצות לימוד", discover_tutors: "מורים פרטיים", discover_helpers: "עמיתים מסייעים", discover_empty: "עדיין אין תוצאות לחיפוש הזה.",
    create_social: "יצירת פעילות חברתית", create_session: "קביעת מפגש לימוד", add_deadline: "הוספת מועד", ask_elysium: "Ely",
    calendar_title: "לוח השנה שלי", calendar_body: "מועדים והפעילויות שאליהן הצטרפתם, בציר זמן אחד.", calendar_upcoming: "קרוב",
    calendar_past: "עבר", calendar_empty: "עדיין לא נקבע דבר.", tools_title: "ערכת הכלים לסטודנט",
    tools_body: "חישוב, חזרה, עזרה אמינה וקישורים רשמיים במקום אחד.", tutors: "מורים פרטיים", helpers: "עמיתים מסייעים",
    no_upcoming: "אין פריטים קרובים", due_today: "היום", tomorrow: "מחר", days: "ימים", pending: "ממתין",
    request_sent: "הבקשה נשלחה", subject: "נושא", preferred_time: "תאריך ושעה מועדפים", message: "הודעה", send_request: "שליחת בקשה",
    profile_public_note: "מידע ציבורי: שם, מקצועות, תיאור ופרטי קשר רק בהסכמתך.", profile_helper_note: "שתפו ניסיון אישי כסטודנטים. זו עזרת עמיתים ולא תפקיד רשמי מטעם האוניברסיטה.",
    profile_setup_helper: "הגדרת פרופיל עמית מסייע", profile_active: "פעיל", profile_pending: "ממתין לאישור", profile_visible: "גלוי", profile_hidden: "מוסתר", profile_hide: "הסתרה", profile_show: "הצגה",
    profile_subjects: "מקצועות, מופרדים בפסיקים", profile_phone: "טלפון או WhatsApp", profile_tutor_bio: "תיאור קצר וניסיון בהוראה", profile_contact_consent: "אני מסכים להציג את פרטי הקשר שלי לסטודנטים",
    profile_help_topics: "נושאי עזרה, מופרדים בפסיקים", profile_helper_bio: "במה תוכלו לעזור לסטודנטים אחרים?", profile_availability: "זמינות", profile_public_contact: "הצגת פרטי הקשר שלי לציבור", profile_contact: "WhatsApp או אימייל", profile_my_groups: "קבוצות הלימוד שלי",
    onboarding_step: "שלב", onboarding_of: "מתוך", onboarding_language_title: "בחרו שפה", onboarding_language_body: "אפשר לעבור בין אנגלית, עברית וערבית בכל רגע.", onboarding_name: "שם מועדף",
    onboarding_university_title: "ספרו לנו היכן אתם לומדים", onboarding_university_body: "כך הפעילויות, העזרה והקישורים הרשמיים יתאימו לקמפוס שלכם.", onboarding_no_university: "עדיין לא נוספו אוניברסיטאות. אפשר להמשיך ולבחור מאוחר יותר.", onboarding_year: "שנת לימודים", onboarding_field: "תחום לימוד", onboarding_field_search: "התחילו להקליד, בחרו תחום או הוסיפו משלכם", onboarding_field_select: "בחרו תחום מוצע או השאירו את מה שהקלדתם",
    onboarding_courses_title: "עצבו את פיד הקמפוס", onboarding_courses_body: "הקורסים הם אופציונליים. תחומי עניין עוזרים ל-Elysium להציע אנשים ופעילויות.", onboarding_courses: "קורסים, מופרדים בפסיקים", onboarding_courses_optional: "אופציונלי. אפשר להתחיל בלי קורסים ולהוסיף בהמשך.", onboarding_interests: "תחומי עניין ותחביבים", onboarding_interest_search: "חיפוש תחביבים", onboarding_add_interest: "הוספת תחביב", onboarding_interest_en: "שם באנגלית", onboarding_interest_he: "שם בעברית", onboarding_interest_save: "הוספת תחביב", onboarding_interest_duplicate: "התחביב כבר קיים ולכן בחרנו אותו עבורכם.",
    onboarding_help_title: "במה Elysium צריכה לעזור?", onboarding_help_body: "בחרו את מה שרלוונטי עכשיו, או המשיכו ללא בחירה.", onboarding_back: "חזרה", onboarding_continue: "המשך", onboarding_finish: "כניסה ל-Elysium", onboarding_side_note: "Elysium מתאימה את מסך הבית לקמפוס, לתחומי העניין ולצרכים שלכם.", campus: "קמפוס", your_university: "האוניברסיטה שלך",
  },
  ar: {
    home_kicker: "حرمك الجامعي، منظّم", home_greeting: "سعداء برؤيتك", home_next: "خطوتك التالية",
    home_clear_title: "أمورك مرتبة الآن", home_clear_body: "أضف موعدًا أو انضم إلى نشاط، وسيُبقي Elysium الخطوة التالية واضحة أمامك.",
    home_ask_title: "Ely", home_ask_body: "احصل على إجابة مركزة حسب جامعتك وجدولك وأهدافك.",
    home_upcoming: "القادم", home_for_you: "مقترح لك", home_social: "تعرّف على أشخاص", home_study: "ادرس مع الآخرين",
    home_academic: "مساعدة أكاديمية", home_tools: "أدوات سريعة", home_deadline: "موعد نهائي", home_event: "نشاط اجتماعي", home_session: "جلسة دراسة",
    see_all: "عرض الكل", open: "مفتوح", join: "انضمام", joined: "منضم", leave: "مغادرة", request: "طلب درس", contact: "تواصل",
    discover_title: "اكتشف الحرم الجامعي", discover_body: "اعثر على أشخاص وجلسات وأنشطة تناسب أسبوعك.",
    discover_search: "ابحث حسب الموضوع أو النشاط أو المساق أو الشخص", discover_social: "اجتماعي", discover_sessions: "جلسات دراسة",
    discover_groups: "مجموعات دراسة", discover_tutors: "مدرسون خصوصيون", discover_helpers: "زملاء للمساعدة", discover_empty: "لا توجد نتائج مطابقة حتى الآن.",
    create_social: "إنشاء نشاط اجتماعي", create_session: "جدولة جلسة دراسة", add_deadline: "إضافة موعد", ask_elysium: "Ely",
    calendar_title: "تقويمي", calendar_body: "المواعيد والأنشطة التي انضممت إليها في خط زمني واحد.", calendar_upcoming: "القادم",
    calendar_past: "السابق", calendar_empty: "لا يوجد شيء مجدول بعد.", tools_title: "أدوات الطالب",
    tools_body: "احسب وراجع واعثر على مساعدة موثوقة وروابط رسمية في مكان واحد.", tutors: "مدرسون خصوصيون", helpers: "زملاء للمساعدة",
    no_upcoming: "لا توجد عناصر قادمة", due_today: "اليوم", tomorrow: "غدًا", days: "أيام", pending: "بانتظار الموافقة",
    request_sent: "تم إرسال الطلب", subject: "الموضوع", preferred_time: "التاريخ والوقت المفضلان", message: "رسالة", send_request: "إرسال الطلب",
    profile_public_note: "المعلومات العامة: الاسم والمواضيع والنبذة وبيانات التواصل فقط عند موافقتك.", profile_helper_note: "شارك خبرتك الشخصية كطالب. هذه مساعدة زملاء وليست وظيفة رسمية من الجامعة.",
    profile_setup_helper: "إعداد ملف زميل للمساعدة", profile_active: "نشط", profile_pending: "بانتظار الموافقة", profile_visible: "ظاهر", profile_hidden: "مخفي", profile_hide: "إخفاء", profile_show: "إظهار",
    profile_subjects: "المواضيع، مفصولة بفواصل", profile_phone: "هاتف أو WhatsApp", profile_tutor_bio: "نبذة قصيرة وخبرة التدريس", profile_contact_consent: "أوافق على عرض بيانات تواصلي للطلاب",
    profile_help_topics: "مواضيع المساعدة، مفصولة بفواصل", profile_helper_bio: "بماذا يمكنك مساعدة الطلاب الآخرين؟", profile_availability: "الأوقات المتاحة", profile_public_contact: "عرض بيانات تواصلي علنًا", profile_contact: "WhatsApp أو بريد إلكتروني", profile_my_groups: "مجموعات دراستي",
    onboarding_step: "الخطوة", onboarding_of: "من", onboarding_language_title: "اختر لغتك", onboarding_language_body: "يمكنك التبديل بين الإنجليزية والعبرية والعربية في أي وقت.", onboarding_name: "الاسم المفضل",
    onboarding_university_title: "أخبرنا أين تدرس", onboarding_university_body: "يساعد ذلك على عرض أنشطة ومساعدة وروابط رسمية مناسبة لحرمك الجامعي.", onboarding_no_university: "لم تتم إضافة جامعات بعد. يمكنك المتابعة واختيار واحدة لاحقًا.", onboarding_year: "السنة الدراسية", onboarding_field: "مجال الدراسة", onboarding_field_search: "ابدأ بالكتابة، اختر مجالًا أو أضف مجالك", onboarding_field_select: "اختر مجالًا مقترحًا أو أبقِ ما كتبته",
    onboarding_courses_title: "خصّص موجز الحرم الجامعي", onboarding_courses_body: "المساقات اختيارية. تساعد الاهتمامات Elysium على اقتراح أشخاص وأنشطة مناسبة.", onboarding_courses: "المساقات، مفصولة بفواصل", onboarding_courses_optional: "اختياري. يمكنك البدء دون مساقات وإضافتها لاحقًا.", onboarding_interests: "الاهتمامات والهوايات", onboarding_interest_search: "ابحث عن هواية", onboarding_add_interest: "إضافة هواية", onboarding_interest_en: "الاسم بالإنجليزية", onboarding_interest_he: "الاسم بالعبرية", onboarding_interest_save: "إضافة الهواية", onboarding_interest_duplicate: "هذه الهواية موجودة، لذلك اخترناها لك.",
    onboarding_help_title: "بماذا تريد من Elysium أن يساعدك؟", onboarding_help_body: "اختر ما يهمك الآن، أو تابع دون اختيار.", onboarding_back: "رجوع", onboarding_continue: "متابعة", onboarding_finish: "الدخول إلى Elysium", onboarding_side_note: "يكيّف Elysium الصفحة الرئيسية حسب حرمك واهتماماتك واحتياجاتك الحالية.", campus: "الحرم الجامعي", your_university: "جامعتك",
  },
};

export function productText(locale, key) {
  return copy[locale]?.[key] ?? copy.en[key] ?? key;
}
